# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: the mofo with the info
email: blog@infomofo.com
description: the official blog of infomofo
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.infomofo.com" # the base hostname & protocol for your site
twitter_username: infomofo
github_username:  infomofo

# Build settings
markdown: kramdown
collections:
  micro:
    output: true
    layout: post
    permalink: /micro/:title
